name: music-box
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # hourly
  push:
    branches: main       # i forgor to change this

jobs:
  musicbox:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - name: Setup Node runtime
       uses: actions/setup-node@v4
       with:
         node-version: '20'
       env:
         ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

     - run: npm install
     - name: Update
       uses: ./
       env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
